### ISSUE TITLE
Whether it can be added depends on different functions

### ISSUE THREAD

**Issue by allChangelove** [hoiheart/vue-diff#10]
details：It means that there is one more props in the component diff, which is all expanded by default. If I pass true, it means that I want to see different components. The same parts of the component will be folded up, and different parts will be expanded by default. That's the requirement. I don't know if I can add it

Urgent needs, I hope you can support it as soon as possible. I hope you can go online as soon as possible. Thank you very much

**Comment by hoiheart** [comment]
Same content as #9
