### ISSUE TITLE
The "theme" property should accept more than 'dark' | 'light' | 'custom'

### ISSUE THREAD

**Issue by ouuan** [hoiheart/vue-diff#32]
For example, I may set `theme` to `custom-dark`/`custom-light` or something else, but now it's limited to `'dark' | 'light' | 'custom'`:

https://github.com/hoiheart/vue-diff/blob/b8258df20485102899f0da359e0fa54522147f72/src/types.ts#L8

I suggest changing it to either `string` or ``` 'dark' | 'light' | `custom${string}` ```.

**Comment by hoiheart** [comment]
@ouuan 
The proposal was released in 1.2.4 🚀
Thanks 👍
