### ISSUE TITLE
Support Vue2

### ISSUE THREAD

**Issue by minseolee** [hoiheart/vue-diff#37]
Hi, thanks for great source

I'm using vue2.6.14 + compisition-api 1.6.2.
I've installed this package, but got 93 warnings 
```
 warning  in ./node_modules/vue-diff/dist/index.es.js

"export 'Fragment' (imported as 'b') was not found in 'vue'
```

It looks like only for vue3, not working at vue2.

Is there any plan to support vue2?

Thanks.

**Comment by minseolee** [comment]
I've converted library as internal, not through npm
It works well at vue 2.6.14 + composition-api 1.6.2
Closing this issue

**Comment by TrongBa** [comment]
Morning bro @minseolee , do you can share source code support vue2 ?
Thank you very much.

**Comment by minseolee** [comment]
@TrongBa Please check this PR https://github.com/spaceone-dev/console/pull/3030

**Comment by TrongBa** [comment]
@minseolee  Thank you.
