### ISSUE TITLE
能否添加只看不同的功能？

### ISSUE THREAD

**Issue by allChangelove** [hoiheart/vue-diff#9]
意思就是组件diff里面多一个props，默认是全部展开的，如果我传true，代表我想看不同，组件相同的地方就收起，不同的地方就默认展开就好，就是这样的需求，不知可否添加一下

**Comment by hoiheart** [comment]
@allChangelove
Hello,
I don't understand the text you wrote.
Sorry. 😭

**Comment by allChangelove** [comment]
title: Whether it can be added depends on different functions

details：It means that there is one more props in the component diff, which is all expanded by default. If I pass true, it means that I want to see different components. The same parts of the component will be folded up, and different parts will be expanded by default. That's the requirement. I don't know if I can add it

**Comment by hoiheart** [comment]
I also reviewed the function, but I was worried that there would be a performance drop if the code folding logic continued to work in real-time comparison.

I'll see if there's a good way, but it'll take some time.

**Comment by allChangelove** [comment]
那就做相关的只看不同的功能，不用和我上面说的一样的，折叠这个可要可不要，你就看着实现类似的功能吧（重点突出只看不同哈，可以加我的微信联系：wjx123syb）

**Comment by allChangelove** [comment]
Then do the related work and only look at the different functions. You don't need to fold this as I said above. You can look at the realization of similar functions (focus on the differences, and you can add my wechat contact: wjx123syb)

**Comment by hoiheart** [comment]
If enable the code folding option, the developer can pass the data by submit method instead of v-model. (maybe...)

But I don't have much time given to this plug-in, so I need a few weeks to develop the function.

I'm sorry.

**Comment by allChangelove** [comment]
Maybe it doesn't need to be folded, that is, if I choose to only look at different data, you can display different data, and the same data can not be displayed directly. How long does the workload take? Thank you very much

**Comment by hoiheart** [comment]
@allChangelove 

Folding props has been added.
https://github.com/hoiheart/vue-diff#props
https://hoiheart.github.io/vue-diff/demo/index.html

I'll develop a function to control each folding later.

Thanks. 😀

**Comment by allChangelove** [comment]
OK, thank you very much. Please let me know when this function is developed
